### PR TITLE
Update progress of module VR xblock

### PR DESCRIPTION
**Pull request by zamanafzal**
This Pr will update the progress of module of VR x-block when a user clicks on that module.
@bradenmacdonald Please have a look into this.

### CODE REVIEW

**Comment by zamanafzal** [comment]
This Pr will update the progress of module of VR x-block when a user clicks on that module.
@xitij2000 Please have a look into this.

**Comment by bradenmacdonald** [comment]
In the future this should use [CompletableXBlockMixin](https://github.com/edx/XBlock/blob/master/xblock/completable.py) but that won't work until we upgrade edx-solutions to the new completion API, so this is fine for now.

**Comment by zamanafzal** [comment]
@bradenmacdonald Should I merge this PR?

**Comment by bradenmacdonald** [comment]
@zamanafzal  This week, @kaizoku from my team will verify that it works and approve the PR and then we'll merge it.

**Comment by kaizoku** [comment]
:+1:

- [✓] I tested this: (installed the branch in my devstack, created test course with virtual reality block, and navigated to the block)
- [✓] I read through the code
- [n/a] I checked for accessibility issues
- [n/a] Includes documentation

**Pull request merged**
