### PR TITLE
MCKIN-24381 Eight language support added

### PR DESCRIPTION
**Pull request by musmanmalik**
Eight language support added

### CODE REVIEW

**Comment by musmanmalik** [comment]
@xitij2000 Please review this.

**Comment by aayushagra** [comment]
@musmanmalik When i tried testing this i saw that many strings, even though they are in the .po files are not actually translated (See my screenshot). Do you have any insight on this?
Screenshot from 2020-10-05 12-45-38
Screenshot from 2020-10-05 12-47-22

CC: @xitij2000

**Comment by musmanmalik** [comment]
@aayushagra That is possible. There might be some strings that are not marked for translations or some other related issue. In this ticket we are just adding translation. We will have other ticket under the heading platform issues in which we will look why some strings not getting translated and will rectify that.

**Comment by aayushagra** [comment]
:+1:

- [x] I tested this: Checked out the PR, ran compile_translations, ran tests, installed it on a juniper devstack & tried all eight languages, making sure there were no errors
- [x] I read through the code
- [ ] I checked for accessibility issues
- [ ] Includes documentation
- [ ] I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository.

**Pull request merged**
